server:
  port: 8088
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.xfqb.rollcall.entity
  #mapper 文件要先存在
  mapperLocations: classpath:mapper/*.xml
---

#开发配置
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/filter?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
 
# druid 监控
#spring监控，hello.controller是我的控制层包名，也可以是服务层，用逗号分隔多个监控内容  
    druid:
      aop-patterns:
      - com.xfqb.rollcall.*
      stat-view-servlet:
        #监控页面登录密码  
        login-password: root
        #监控页面登录用户名  
        login-username: admin
      web-stat-filter:
        session-stat-max-count: 
 